import type { Metadata } from 'next'
import '../globals.css'

export const metadata: Metadata = {
  title: 'dfed movies pet project',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      {/* <html lang="en">
        <head>
          <meta charSet="UTF-8" />
          <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0"
          />
          <title>Movie App</title>
        </head>
        <body>{children}</body>
      </html> */}
      <>{children}</>
    </>
  )
}
